version: '3'
services:
  app:
    build: .
    container_name: orderful-converter-app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
